basics/blog/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'subscriptions/new' => 'subscriptions#new', as: :new_subscription
  post 'subscriptions/create' => 'subscriptions#create'

  resources :articles
  
  root 'welcome#index'

end

basics/blog/app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
end

basics/blog/app/models/stripe_customer_mapper.rb
class StripeCustomerMapper
  def initialize(customer)
    @customer = customer
  end
  
  def credit_card_expiration_month
    @customer.sources.data[0].exp_month
  end

  def credit_card_expiration_year
    @customer.sources.data[0].exp_year
  end

  def credit_card_last4digits
    @customer.sources.data[0].last4
  end
  
  def customer_token
    @customer.id
  end

end

basics/blog/app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user  
  
  def self.save_details(stripe_customer, user, plan_name)
    mapper = StripeCustomerMapper.new(stripe_customer)
    user.create_subscription(stripe_customer_token: mapper.customer_token,
                             plan_name:             plan_name,
                             last4digits:      mapper.credit_card_last4digits,
                             expiration_month: mapper.credit_card_expiration_month,
                             expiration_year:  mapper.credit_card_expiration_year)
  end
end

basics/blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :subscription
end

basics/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

basics/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: 'user', password: 'secret', only: [:create, :edit, :update, :destroy, :new]
    
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def create
    allowed_params = params.require(:article).permit(:title, :description)
    @article = Article.new(allowed_params)
    
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    allowed_params = params.require(:article).permit(:title, :description)
    article = Article.find(params[:id])
    article.update_attributes(allowed_params)
    
    redirect_to articles_path
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    
    redirect_to articles_path
  end
end

basics/blog/app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  layout 'stripe'  
  
  def new
    @plan_name = params[:plan_name]      
  end

  def create    
    stripe_customer = StripeGateway::Subscription.create(current_user.email, params[:stripeToken], params[:plan_name])
    Subscription.save_details(stripe_customer, current_user, params[:plan_name])
  end
end

basics/blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

basics/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

basics/blog/app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

basics/blog/app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2><%= pluralize(@article.errors.count, "error") %> prohibited
    this article from being saved:</h2>

  <ul>
  <% @article.errors.full_messages.each do |m| %>
    <li><%= m %></li>
  <% end %>
  </ul>
<% end %>


<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

basics/blog/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

basics/blog/app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<table >
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, article %></td>
        <td><%= article.description %></td>
        <td>
          <%= link_to 'Edit', edit_article_path(article) %>
          <%= link_to 'Delete', 
											 article_path(article), 
											 :method => :delete, 
											 :confirm => 'Are you sure?' %>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Article', new_article_path %>

basics/blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

basics/blog/app/views/articles/show.html.erb
<p>
  <%= @article.title %><br>
</p>

<p>
  <%= @article.description %><br>
</p>

basics/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

   <%= link_to 'Register', new_user_registration_path %>

   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

basics/blog/app/views/layouts/stripe.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Striped</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  
  <%= javascript_include_tag 'https://js.stripe.com/v2/' %>
  <%= tag :meta, :name => "stripe-key", :content => 'pk_test_GxDbP7Q6f4GkaUe0I0LrbQSz' %>

  <script type="text/javascript">
    // This identifies your website in the createToken call below
    Stripe.setPublishableKey($('meta[name="stripe-key"]').attr('content'));
  
    var stripeResponseHandler = function(status, response) {
      var $form = $('#payment-form');

      if (response.error) {
        // Show the errors on the form
        $form.find('.payment-errors').text(response.error.message);
        $form.find('button').prop('disabled', false);
      } else {
        // token contains id, last4, and card type
        var token = response.id;

        // Insert the token into the form so it gets submitted to the server
        $form.append($('<input type="hidden" name="stripeToken" />').val(token));

        // and re-submit
        $form.get(0).submit();
      }
    };
    
    jQuery(function($) {
      $('#payment-form').submit(function(event) {

        var $form = $(this);

        // Disable the submit button to prevent repeated clicks
        $form.find('submit').prop('disabled', true);

        Stripe.card.createToken($form, stripeResponseHandler);

        // Prevent the form from submitting with the default action
        return false;
      });
    });
      
  </script>  
   
	<%= csrf_meta_tags %>
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body data-no-turbolink>

	<div class='container'>
		<%= yield %>
	</div>
	
  </body>
</html>

basics/blog/app/views/subscriptions/create.html.erb
You are now on gold plan.

basics/blog/app/views/subscriptions/new.html.erb
<form action="create" method="POST" id="payment-form">
  <span class="payment-errors">
  	<noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </span>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
  <%= hidden_field_tag :plan_name, @plan_name %>

  <% if @error_message %>
	<%= @error_message %>
  <% end %>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration</span>
<%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month", data: {stripe: "exp-month"}} %>
      
    </label>
    <span>/</span>
	<%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year", data: {stripe: "exp-year"}} %>
	
  </div>

  <button type="submit" class='btn btn-primary'>Subscribe Me</button>

</form>

basics/blog/app/views/welcome/index.html.erb
<h1>My Blog</h1>

	<%= link_to 'Gold', new_subscription_path(:plan_name => 'gold') %> <br/>
	<%= link_to 'Silver', new_subscription_path(:plan_name => 'silver') %> <br/>

<%= link_to 'My Blog', articles_path %>